### ISSUE TITLE
no content

### ISSUE THREAD

**Issue by NimaFakoor** [cs-um/cs-um.github.io#1]
push content please

**Comment by mamintoosi** [comment]
جناب آقای فکور سلام و عرض ادب.

این مخزن تقریبا خالی رو برای گروه علوم کامپیوتر فردوسی ایجاد کرده‌ام.
یک تم الکی گذاشتم که خیلی خالی نباشه.
تمایل به کمک دارید؟
خوشحال می‌شوم مشتاقانی در کنارمان باشند.

**Comment by NimaFakoor** [comment]
سلام و عرض ادب استاد عزیز
ممنون از پاسخگویی شما
باعث افتخار است در زمان آزاد، در تکمیل محتوای این مخزن و گسترش آن طبق سرفصل، کمک کنم.
لطفا درصورت امکان شناسه بنده را به عنوان نگهدارنده این پروژه اضافه کنید.
با احترام

@NimaFakoor
n.fakoor0@gmail.com

**Comment by mamintoosi** [comment]
بزرگوارید.
نگهدارنده شدید.
ضمنا چون موضوع مربوطه در کلاس کارگاه برنامه‌سازی پیشرفته مطرح است شما رو در vu‌ به این کلا اضافه کردم.
